### ISSUE TITLE
Unable to craft furnace items while using Magic Storage and Terraria Ambience.

### ISSUE THREAD

**Issue by Feathersongs** [RighteousRyan1/TerrariaAmbience#1]
**Location:** Any Magic Storage Crafting Interface with a furnace or hellforge.

**Observed Behavior:** Attempting to craft using any items that require the furnace or hellforge writes the following error to the screen and does not craft the item or consume the ores.

**Expected Behavior:** The selected item should be crafted, and possibly the sound should play.

**Steps to reproduce:** 1.)  Access any Crafting Interface that holds a furnace or hellforge.
2.) Try to craft any items that require the Furnace and play a sound, such as any bars.

![Error](https://user-images.githubusercontent.com/71628680/112280928-e3ff3d00-8c5b-11eb-880b-9d806710bac6.png)

**Comment by RighteousRyan1** [comment]
Wow. I finally notice this issue (even though it's mostly unfixable on my end) exactly a year after it was created.

But yeah, only way it gets fixed is via the maintainer(s) of MagicStorage (absoluteAquarian, Exterminator, etc) fix it. Thanks for the heads up for others though.
